image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [863.47497,   0.     , 636.86582,
           0.     , 863.71182, 482.66553,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.104875, 0.093450, -0.000067, 0.000373, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [851.29381,   0.     , 637.66885,   0.     ,
           0.     , 850.18261, 483.87513,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
